{
  "jobs": {
    "deb": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v7.0.1",
          "with": {
            "path": "repo"
          }
        },
        {
          "uses": "${{ matrix.release.image }}",
          "with": {
            "args": "bash repo/.github/deb-workflow/build.sh ${{ matrix.release.name }} ${{ matrix.release.nr }} || echo W: nonzero exit status, failing later"
          }
        },
        {
          "uses": "actions/upload-artifact@v7.0.1",
          "with": {
            "archive": true,
            "compression-level": 9,
            "if-no-files-found": "error",
            "name": "result-${{ matrix.release.nr }}",
            "path": "result-${{ matrix.release.nr }}"
          }
        },
        {
          "uses": "${{ matrix.release.image }}",
          "with": {
            "args": "bash repo/.github/deb-workflow/post.sh"
          }
        }
      ],
      "strategy": {
        "matrix": {
          "release": [
            {
              "image": "docker://debian:trixie",
              "name": "trixie",
              "nr": "13"
            },
            {
              "image": "docker://debian:sid",
              "name": "sid",
              "nr": "sid"
            }
          ]
        }
      }
    }
  },
  "name": "deb packages",
  "on": {
    "push": {
      "branches": [
        "deb-test"
      ]
    },
    "workflow_dispatch": null
  },
  "permissions": {
    "contents": "read",
    "id-token": "write"
  }
}
